### ISSUE TITLE
Remove option to pass reads to RGI in Galaxy

### ISSUE THREAD

**Issue by apetkau** [arpcard/rgi_wrapper#4]
As per https://github.com/arpcard/rgi/issues/35 there is no support for the **read** input type as it's being moved to a separate section of the program.

I think we should remove the option to pass reads (e.g. in https://github.com/arpcard/rgi_wrapper/blob/master/rgi.xml#L38) and also mentioning reads (e.g., in https://github.com/arpcard/rgi_wrapper/blob/master/rgi.xml#L36) until this support is added.

What do you think @raphenya @mjram0s ?

**Comment by raphenya** [comment]
@apetkau Yes, please. @mjram0s Please also remove `wgs` option: https://github.com/arpcard/rgi_wrapper/blob/master/rgi.xml#L41

**Comment by mjram0s** [comment]
See #6 for changes

**Comment by apetkau** [comment]
Fixed in #6
