### ISSUE TITLE
State of main toolshed

### ISSUE THREAD

**Issue by innovate-invent** [arpcard/rgi_wrapper#7]
Hi, I am interested in using this in my instance of Galaxy.
There is an outdated version in the test tool shed and a seemingly broken repo in the main tool shed.
Can you update the main tool shed?

Thanks

**Comment by raphenya** [comment]
@innovate-invent Thank you. We will be updating this soon.

**Comment by raphenya** [comment]
@innovate-invent RGI version 4.2.2 is now on Galaxy Main and Test toolshed.

**Comment by innovate-invent** [comment]
Thanks from Brinkman Lab!
