### ISSUE TITLE
Update to version 5.1

### ISSUE THREAD

**Issue by innovate-invent** [arpcard/rgi_wrapper#9]
Please update the wrapper to version 5.1 and publish to the Galaxy Main toolshed.

**Comment by raphenya** [comment]
@innovate-invent Will do. thanks again.

**Comment by raphenya** [comment]
@innovate-invent pushed RGI version 5.1.0 to test and main toolsheds. Note the wrapper doesn't include other parameters yet.

**Comment by innovate-invent** [comment]
Thanks, it might help you to adapt this:
https://github.com/brinkmanlab/galaxy-tools/blob/master/.github/workflows/main-shed.yml

I think you could actually just drop it into your repo and it'll work. You have to set the SHED_KEY secret.
